# name: Unsecured workflows
 
# on:
#   push:
#     branches:
#       main
 
# jobs:
#   build:
#     runs-on: thesis-vm
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Build image
#         run: docker build -t pungpeee19/2-big-code-juiceshop:latest .

#       - name: Push image to Docker Hub
#         run: |
#           docker login -u pungpeee19 -p ${{ secrets.DOCKER_HUB_TOKEN }}
#           docker push pungpeee19/2-big-code-juiceshop:latest
 
#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
 
#     steps:
#       - name: Set up SSH
#         uses: webfactory/ssh-agent@v0.5.3
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Deploy to Remote Server
#         run: |
#           ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
          
#           # Log in to Docker Hub
#           echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u pungpeee19 --password-stdin

#           # Pull the latest image
#           docker pull pungpeee19/2-big-code-juiceshop:latest

#           # Stop and remove the existing container if it exists
#           if [ $(docker ps -q -f name=2-big-code-juiceshop) ]; then
#             docker stop 2-big-code-juiceshop
#             docker rm 2-big-code-juiceshop
#           fi

#           # Run the new container
#           docker run -d --restart=always -p 1001:3000 --name 2-big-code-juiceshop pungpeee19/2-big-code-juiceshop:latest

#           # Verify running containers
#           docker ps -a
          
#           EOF

#       # - name: Run StackHawk DAST scan
#       #   uses: hawkeyesec/scanner-action@v1
#       #   with:
#       #     apiKey: ${{ secrets.STACKHAWK_API_KEY }}
#       #     configFile: hawk.yaml
          

          

#       # - name: Login to Docker Hub & Deploy code and start Docker container
#       #   run: |
#       #       docker login -u pungpeee19 -p ${{ secrets.DOCKER_HUB_TOKEN }}
#       #       ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} 
#       #       docker pull pungpeee19/2-big-code-juiceshop:latest
#       #       docker images
#       #       docker run -d --restart=always -p 1001:3000 \
#       #           --name 2-big-code-juiceshop \
#       #           pungpeee19/2-big-code-juiceshop:latest
